[project]
name = "django-tagging"
version = "0.7.0+dismine.1"
description = "Generic tagging application for Django"
authors = [
  {name = "Jonathan Buchanan", email = "jonathan.buchanan@gmail.com"}
]
maintainers = [
    {name = "Roman Telezhynskyi",email = "dismine@gmail.com"}
]
license = { file = "LICENSE.txt" }
keywords = ["django, tag, tagging"]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "django (>=5.2.0,<6.0.0)"
]
classifiers=[
    'Framework :: Django',
    'Framework :: Django :: 5.2',
    'Environment :: Web Environment',
    'Operating System :: OS Independent',
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: BSD License',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Topic :: Utilities',
    'Topic :: Software Development :: Libraries :: Python Modules'
]
[project.urls]
Repository = "https://github.com/dismine/django-tagging"
Changelog = "https://github.com/dismine/django-tagging/blob/develop/CHANGELOG"

[tool.poetry]
exclude = ["**/tests"]

include = ["docs", "CHANGELOG", "LICENSE.txt"]
packages = [{ include = "tagging" }]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
tox = "^4.26.0"
django-upgrade = "^1.25.0"
flake8 = "^7.2.0"
pytest = "^8.4.0"
pytest-django = "^4.11.1"
pytest-cov = "^6.1.1"
black = "^25.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
