[tox]
envlist = py-django{52},flake8,coveralls
isolated_build = true
skip_missing_interpreters = true


[testenv]
description = Run tests with pytest
passenv = DJANGO_SETTINGS_MODULE
setenv =
    PYTHONPATH = {toxinidir}
    DJANGO_SETTINGS_MODULE = tagging.tests.settings

[testenv:py-django52]
deps =
    poetry
commands_pre =
    python --version
    poetry add Django==5.2.*
    poetry install --with dev
commands = poetry run pytest

[testenv:flake8]
description = Lint with flake8
skip_install = true
deps = flake8
commands = flake8 tagging
